import { beforeAll, describe, expect, it } from "vitest";
import ExcelJS from "exceljs";
import { db, deps, issueInput, program, staff, storage } from "../helpers";
import {
  bulkResultsCsv,
  bulkTemplateCsv,
  confirmBulkJob,
  createBulkJob,
  csvCell,
  normalizeDate,
  parseCsv,
  processBulkChunk,
  retryFailedRows,
} from "@/src/modules/credentials/bulk";
import { issueCredential } from "@/src/modules/credentials/service";
import type { CredentialStorage } from "@/src/modules/credentials/storage";

let P: Awaited<ReturnType<typeof program>>;
let issuer: Awaited<ReturnType<typeof staff>>;
const enc = (s: string) => new TextEncoder().encode(s);

beforeAll(async () => {
  P = await program({ code: "BLK" });
  issuer = await staff("ISSUER");
});

async function job(csv: string, over: Partial<Parameters<typeof createBulkJob>[0]> = {}) {
  return createBulkJob({ bytes: enc(csv), fileName: "cohort.csv", courseId: P.course.id, defaultBatchId: P.batch.id, sendEmail: true, ...over }, issuer, deps());
}
async function rows(jobId: string) {
  return db.credentialBulkRow.findMany({ where: { job_id: jobId }, orderBy: { row_number: "asc" } });
}
async function drain(jobId: string, d = deps()) {
  for (let i = 0; i < 50; i++) {
    const r = await processBulkChunk(jobId, issuer, d, 3);
    if (r.remaining === 0) return;
  }
}
const u = () => Math.random().toString(36).slice(2, 8);

describe("parsing", () => {
  it("handles quotes, commas, CRLF and BOM", () => {
    const s = parseCsv('﻿full_name,email\r\n"Raman, Priya",p@x.com\r\n"Say ""hi""",q@x.com\n');
    expect(s.headers).toEqual(["full_name", "email"]);
    expect(s.rows).toEqual([["Raman, Priya", "p@x.com"], ['Say "hi"', "q@x.com"]]);
  });
  it("accepts ISO and Indian dates only, never guessing", () => {
    expect(normalizeDate("2026-07-15")).toBe("2026-07-15");
    expect(normalizeDate("15/07/2026")).toBe("2026-07-15");
    expect(normalizeDate("5-7-2026")).toBe("2026-07-05");
    expect(normalizeDate("07/15/2026")).toBeNull(); // US order is refused (month 15)
    expect(normalizeDate("July 15 2026")).toBeNull();
    expect(normalizeDate("31/02/2026")).toBeNull();
  });
  it("the downloadable template is itself a valid import", async () => {
    const tpl = bulkTemplateCsv("BLK").replace("Cohort 1 — September 2026", "Cohort A").replace("priya.raman@example.com", `tpl-${u()}@example.com`);
    const j = await job(tpl);
    expect((await rows(j.id))[0].validation).toBe("VALID");
  });
});

describe("validation before issuance", () => {
  it("rejects files without required columns or with system-generated columns", async () => {
    await expect(job("name,email\nA,a@x.com\n")).rejects.toThrow(/completion_date/);
    await expect(job("full_name,email,completion_date,certificate_id\nA B,a@x.com,2026-07-01,MSC-1\n")).rejects.toThrow(/generated by the system/);
  });

  it("classifies every row and issues nothing until confirmed", async () => {
    const existingEmail = `exists-${u()}@example.com`;
    await issueCredential(issueInput(P, { email: existingEmail, fullName: "Existing Person" }), issuer, deps());
    const before = await db.credential.count();
    const j = await job(
      [
        "full_name,email,completion_date,cohort",
        `Asha Verma,asha-${u()}@example.com,15/07/2026,`, // 2 valid
        `Bad Email,not-an-email,2026-07-15,`, // 3 error
        `Future Date,f-${u()}@example.com,2099-01-01,`, // 4 error
        `Existing Person,${existingEmail},2026-07-15,`, // 5 warning (duplicate)
        `Nobody,n-${u()}@example.com,2026-07-15,Cohort Z`, // 6 error (unknown cohort)
        `Dup One,dup@example.com,2026-07-15,Cohort B`, // 7 valid (cohort by name)
        `Dup Two,dup@example.com,2026-07-15,Cohort B`, // 8 error (dup in file)
        `${"Supercalifragilisticexpialidocious".repeat(3)},long-${u()}@example.com,2026-07-15,`, // 9 error (doesn't fit)
      ].join("\n"),
    );
    const r = await rows(j.id);
    expect(r.map((x) => x.validation)).toEqual(["VALID", "ERROR", "ERROR", "WARNING", "ERROR", "VALID", "ERROR", "ERROR"]);
    expect(JSON.stringify(r[3].messages)).toMatch(/Already has active credential/);
    expect(JSON.stringify(r[6].messages)).toMatch(/Duplicate of row 7/);
    expect((r[5].input as { batchId: string }).batchId).toBe(P.batch2.id);
    expect(await db.credential.count()).toBe(before);
    await expect(processBulkChunk(j.id, issuer, deps())).rejects.toMatchObject({ code: "NOT_ALLOWED" });

    await confirmBulkJob(j.id, issuer, deps());
    await confirmBulkJob(j.id, issuer, deps()); // idempotent
    await drain(j.id);
    const done = await rows(j.id);
    expect(done.map((x) => x.outcome)).toEqual(["SUCCESS", "SKIPPED", "SKIPPED", "DUPLICATE", "SKIPPED", "SUCCESS", "SKIPPED", "SKIPPED"]);
    expect(await db.credential.count()).toBe(before + 2);
    expect((await db.credentialBulkJob.findUniqueOrThrow({ where: { id: j.id } })).status).toBe("COMPLETED");
    const bulkCreds = await db.credential.findMany({ where: { id: { in: done.map((x) => x.credential_id!).filter(Boolean) } } });
    expect(bulkCreds.every((c) => c.source === "BULK" && c.status === "VALID")).toBe(true);
  });
});

describe("idempotent processing", () => {
  it("concurrent processors and re-runs never duplicate a row", async () => {
    const lines = ["full_name,email,completion_date", ...Array.from({ length: 12 }, (_, i) => `Learner ${i},conc-${u()}-${i}@example.com,2026-07-15`)];
    const j = await job(lines.join("\n"));
    await confirmBulkJob(j.id, issuer, deps());
    await Promise.all([drain(j.id), drain(j.id), drain(j.id)]);
    await drain(j.id);
    const r = await rows(j.id);
    expect(r.every((x) => x.outcome === "SUCCESS")).toBe(true);
    expect(await db.credential.count({ where: { idempotency_key: { startsWith: `bulk:${j.id}:` } } })).toBe(12);
  });

  it("retrying failed rows completes them without touching successes", async () => {
    let calls = 0;
    const flaky: CredentialStorage = {
      put: async (k, b, t) => {
        calls++;
        if (calls % 2 === 0) throw new Error("storage hiccup");
        return storage.put(k, b, t);
      },
      get: (k) => storage.get(k),
    };
    const lines = ["full_name,email,completion_date", ...Array.from({ length: 6 }, (_, i) => `Retry ${i},retry-${u()}-${i}@example.com,2026-07-15`)];
    const j = await job(lines.join("\n"));
    await confirmBulkJob(j.id, issuer, deps());
    await drain(j.id, deps({ storage: flaky }));
    const first = await rows(j.id);
    const failed = first.filter((x) => x.outcome === "FAILED");
    const succeeded = first.filter((x) => x.outcome === "SUCCESS");
    expect(failed.length).toBeGreaterThan(0);
    expect(succeeded.length).toBeGreaterThan(0);

    await retryFailedRows(j.id, issuer, deps());
    await drain(j.id);
    const after = await rows(j.id);
    expect(after.every((x) => x.outcome === "SUCCESS")).toBe(true);
    for (const s of succeeded) expect(after.find((x) => x.id === s.id)!.credential_id).toBe(s.credential_id);
    expect(await db.credential.count({ where: { idempotency_key: { startsWith: `bulk:${j.id}:` } } })).toBe(6);
  });
});

describe("xlsx and export", () => {
  it("reads .xlsx including real date cells", async () => {
    const wb = new ExcelJS.Workbook();
    const ws = wb.addWorksheet("Cohort");
    ws.addRow(["Full Name", "Email", "Completion Date"]);
    ws.addRow(["Kiran Das", `kiran-${u()}@example.com`, new Date(Date.UTC(2026, 6, 15))]);
    const buf = new Uint8Array(await wb.xlsx.writeBuffer());
    const j = await createBulkJob({ bytes: buf, fileName: "c.xlsx", courseId: P.course.id, defaultBatchId: null, sendEmail: false }, issuer, deps());
    const [r] = await rows(j.id);
    expect(r.validation).toBe("VALID");
    expect((r.input as { completionDate: string }).completionDate).toBe("2026-07-15");
  });

  it("neutralizes formula injection in exported cells", async () => {
    expect(csvCell("=HYPERLINK(\"http://evil\")")).toBe(`"'=HYPERLINK(""http://evil"")"`);
    expect(csvCell("+1")).toBe("'+1");
    expect(csvCell("Priya")).toBe("Priya");
    const j = await job(`full_name,email,completion_date\n=cmd|' /C calc'!A0,inj-${u()}@example.com,2026-07-15\n`);
    const csv = await bulkResultsCsv(j.id, true, deps());
    expect(csv).toContain("'=cmd");
    expect(csv.split("\r\n")[1].startsWith("2,'=cmd")).toBe(true);
  });

  it("results export omits email for roles without private access", async () => {
    const j = await job(`full_name,email,completion_date\nNo Email Export,noexp-${u()}@example.com,2026-07-15\n`);
    const csv = await bulkResultsCsv(j.id, false, deps());
    expect(csv).not.toContain("noexp-");
  });
});
