import "server-only";
import ExcelJS from "exceljs";
import { createHash } from "node:crypto";
import type { Prisma, StaffUser } from "@/src/generated/prisma/client";
import { CredentialError } from "./errors";
import { indianDate, parseISODate, toISODate } from "./dates";
import { dedupeKey } from "./dedupe";
import { preflightCertificate } from "./render";
import { defaultDeps, issueCredential, type CredentialDeps } from "./service";
import { parseTemplateSpec } from "./template-config";
import { generateCertificateId } from "./identifiers";
import { verificationUrl } from "./config";

/**
 * Bulk (cohort) issuance:
 *   upload → parse → normalize → validate every row → preview → confirm →
 *   process in small chunks → row-level results → export.
 *
 * Nothing is issued before confirmation. Each row's idempotency key is
 * deterministic (bulk:<job>:<row>), so re-running a chunk, a double-click, a
 * second browser tab or a "retry failed rows" can never create a second
 * credential for a row that already succeeded.
 */

export const MAX_FILE_BYTES = 2 * 1024 * 1024;
export const MAX_ROWS = 1000;

export const BULK_COLUMNS = {
  required: ["full_name", "email", "completion_date"] as const,
  optional: ["program_code", "cohort", "external_learner_ref"] as const,
  /** Generated by the system; refused if present so nobody can pick their own IDs. */
  forbidden: ["certificate_id", "verification_token", "token"] as const,
  /** Accepted in the PRD's suggested schema but not honoured in MVP (would allow back-dating). */
  ignored: ["issue_date", "expires_at"] as const,
};

export function bulkTemplateCsv(programCode = "FND"): string {
  return [
    "full_name,email,completion_date,program_code,cohort,external_learner_ref",
    `Priya Raman,priya.raman@example.com,15/07/2026,${programCode},Cohort 1 — September 2026,`,
  ].join("\r\n") + "\r\n";
}

const HEADER_ALIASES: Record<string, string> = {
  name: "full_name",
  full_name: "full_name",
  fullname: "full_name",
  learner_name: "full_name",
  learner: "full_name",
  email: "email",
  e_mail: "email",
  email_address: "email",
  completion_date: "completion_date",
  completed_on: "completion_date",
  date_of_completion: "completion_date",
  program_code: "program_code",
  course_code: "program_code",
  cohort: "cohort",
  batch: "cohort",
  cohort_name: "cohort",
  external_learner_ref: "external_learner_ref",
  external_ref: "external_learner_ref",
  certificate_id: "certificate_id",
  verification_token: "verification_token",
  token: "token",
  issue_date: "issue_date",
  expires_at: "expires_at",
};

const normHeader = (h: string) =>
  h.replace(/^﻿/, "").trim().toLowerCase().replace(/[^a-z0-9]+/g, "_").replace(/^_|_$/g, "");

// ── Parsing ───────────────────────────────────────────────────────

type Cell = string | Date | null;
export type ParsedSheet = { headers: string[]; rows: Cell[][] };

/** RFC 4180 CSV: quoted fields, escaped quotes, CRLF/LF, BOM. */
export function parseCsv(text: string): ParsedSheet {
  const src = text.replace(/^﻿/, "");
  const out: string[][] = [];
  let row: string[] = [];
  let field = "";
  let quoted = false;
  for (let i = 0; i < src.length; i++) {
    const ch = src[i];
    if (quoted) {
      if (ch === '"') {
        if (src[i + 1] === '"') {
          field += '"';
          i++;
        } else quoted = false;
      } else field += ch;
      continue;
    }
    if (ch === '"' && field === "") quoted = true;
    else if (ch === ",") {
      row.push(field);
      field = "";
    } else if (ch === "\n" || ch === "\r") {
      if (ch === "\r" && src[i + 1] === "\n") i++;
      row.push(field);
      out.push(row);
      row = [];
      field = "";
    } else field += ch;
    if (out.length > MAX_ROWS + 1) break;
  }
  if (quoted) throw new CredentialError("The CSV has an unclosed quote.", "VALIDATION");
  if (field !== "" || row.length) {
    row.push(field);
    out.push(row);
  }
  const nonEmpty = out.filter((r) => r.some((c) => c.trim() !== ""));
  const [headers = [], ...rows] = nonEmpty;
  return { headers, rows };
}

function cellValue(v: ExcelJS.CellValue): Cell {
  if (v === null || v === undefined) return null;
  if (v instanceof Date) return v;
  if (typeof v === "string" || typeof v === "number" || typeof v === "boolean") return String(v);
  if (typeof v === "object") {
    if ("richText" in v && Array.isArray(v.richText)) return v.richText.map((r) => r.text).join("");
    if ("text" in v && typeof v.text === "string") return v.text; // hyperlink
    if ("result" in v) return cellValue(v.result as ExcelJS.CellValue); // formula: use cached result only
  }
  return null;
}

export async function parseXlsx(bytes: Uint8Array): Promise<ParsedSheet> {
  const wb = new ExcelJS.Workbook();
  try {
    await wb.xlsx.load(Buffer.from(bytes) as unknown as ArrayBuffer);
  } catch {
    throw new CredentialError("That file could not be read as an Excel workbook.", "VALIDATION");
  }
  const ws = wb.worksheets[0];
  if (!ws) throw new CredentialError("The workbook has no sheets.", "VALIDATION");
  if (ws.rowCount > MAX_ROWS + 1) throw new CredentialError(`Too many rows (max ${MAX_ROWS} per upload).`, "VALIDATION");
  const all: Cell[][] = [];
  ws.eachRow({ includeEmpty: false }, (r) => {
    const cells: Cell[] = [];
    for (let c = 1; c <= Math.min(ws.columnCount, 30); c++) cells.push(cellValue(r.getCell(c).value));
    all.push(cells);
  });
  const [headerCells = [], ...rows] = all;
  return { headers: headerCells.map((h) => (h instanceof Date ? "" : String(h ?? ""))), rows };
}

export async function parseUpload(bytes: Uint8Array): Promise<ParsedSheet> {
  if (bytes.byteLength === 0) throw new CredentialError("The file is empty.", "VALIDATION");
  if (bytes.byteLength > MAX_FILE_BYTES) throw new CredentialError("The file is larger than 2 MB. Split it into smaller cohorts.", "VALIDATION");
  const isZip = bytes[0] === 0x50 && bytes[1] === 0x4b && bytes[2] === 0x03 && bytes[3] === 0x04;
  if (isZip) return parseXlsx(bytes);
  let text: string;
  try {
    text = new TextDecoder("utf-8", { fatal: true }).decode(bytes);
  } catch {
    throw new CredentialError("Upload a CSV (UTF-8) or an .xlsx file.", "VALIDATION");
  }
  const sheet = parseCsv(text);
  if (sheet.rows.length > MAX_ROWS) throw new CredentialError(`Too many rows (max ${MAX_ROWS} per upload).`, "VALIDATION");
  return sheet;
}

// ── Normalization ─────────────────────────────────────────────────

/** Dates: ISO (YYYY-MM-DD), Indian DD/MM/YYYY or DD-MM-YYYY, or a real Excel date. Anything else is refused, never guessed. */
export function normalizeDate(v: Cell): string | null {
  if (v instanceof Date) {
    if (Number.isNaN(v.getTime())) return null;
    return toISODate(new Date(Date.UTC(v.getUTCFullYear(), v.getUTCMonth(), v.getUTCDate())));
  }
  const s = (v ?? "").trim();
  if (parseISODate(s)) return s;
  const m = /^(\d{1,2})[/.-](\d{1,2})[/.-](\d{4})$/.exec(s);
  if (m) {
    const iso = `${m[3]}-${m[2].padStart(2, "0")}-${m[1].padStart(2, "0")}`;
    return parseISODate(iso) ? iso : null;
  }
  return null;
}

const normText = (v: Cell) => (v instanceof Date ? "" : (v ?? "").normalize("NFC").replace(/\s+/g, " ").trim());

export type RowInput = {
  fullName: string;
  email: string;
  completionDate: string;
  batchId: string | null;
  cohortName: string | null;
  externalRef: string | null;
};
export type RowMessage = { level: "error" | "warning"; text: string };

// ── Validation → job ──────────────────────────────────────────────

export async function createBulkJob(
  opts: { bytes: Uint8Array; fileName: string; courseId: string; defaultBatchId: string | null; sendEmail: boolean },
  actor: StaffUser,
  deps: CredentialDeps = defaultDeps(),
) {
  const { db } = deps;
  const course = await db.course.findUnique({ where: { id: opts.courseId }, include: { batches: true } });
  if (!course) throw new CredentialError("Program not found.", "NOT_FOUND");
  if (!course.code) throw new CredentialError("This program has no program code yet.", "CONFIG");
  const template = await db.certificateTemplate.findFirst({ where: { course_id: course.id, status: "ACTIVE" } });
  if (!template) throw new CredentialError("This program has no active certificate template.", "CONFIG");
  if (opts.defaultBatchId && !course.batches.some((b) => b.id === opts.defaultBatchId)) {
    throw new CredentialError("That cohort does not belong to this program.", "VALIDATION");
  }

  const sheet = await parseUpload(opts.bytes);
  const headers = sheet.headers.map((h) => HEADER_ALIASES[normHeader(h)] ?? normHeader(h));
  const forbidden = headers.filter((h) => (BULK_COLUMNS.forbidden as readonly string[]).includes(h));
  if (forbidden.length) {
    throw new CredentialError(`Remove the ${forbidden.join(", ")} column: certificate IDs and tokens are generated by the system.`, "VALIDATION");
  }
  const missing = BULK_COLUMNS.required.filter((r) => !headers.includes(r));
  if (missing.length) throw new CredentialError(`Missing required column(s): ${missing.join(", ")}. Download the template for the exact format.`, "VALIDATION");
  if (sheet.rows.length === 0) throw new CredentialError("The file has a header row but no learners.", "VALIDATION");
  const ignored = headers.filter((h) => (BULK_COLUMNS.ignored as readonly string[]).includes(h));
  const col = (name: string) => headers.indexOf(name);

  const spec = parseTemplateSpec(template);
  const today = indianDate(deps.now());
  const programTitle = course.certificate_title?.trim() || course.name;
  const batchByName = new Map(course.batches.map((b) => [b.name.trim().toLowerCase(), b]));
  const seen = new Map<string, number>();

  const rows: { row_number: number; input: RowInput; validation: "VALID" | "WARNING" | "ERROR"; messages: RowMessage[] }[] = [];
  for (let i = 0; i < sheet.rows.length; i++) {
    const r = sheet.rows[i];
    const rowNumber = i + 2; // spreadsheet row, header is row 1
    const get = (name: string) => (col(name) >= 0 ? r[col(name)] ?? null : null);
    const messages: RowMessage[] = [];
    const fullName = normText(get("full_name"));
    const email = normText(get("email")).toLowerCase();
    const completionDate = normalizeDate(get("completion_date"));
    const programCode = normText(get("program_code")).toUpperCase();
    const cohortName = normText(get("cohort")) || null;
    const externalRef = normText(get("external_learner_ref")).slice(0, 120) || null;

    if (fullName.length < 2) messages.push({ level: "error", text: "Full name is missing." });
    if (fullName.length > 120) messages.push({ level: "error", text: "Full name is longer than 120 characters." });
    if (!/^[^@\s]+@[^@\s]+\.[^@\s]+$/.test(email) || email.length > 254) messages.push({ level: "error", text: "Email is missing or invalid." });
    if (!completionDate) messages.push({ level: "error", text: "Completion date must be YYYY-MM-DD or DD/MM/YYYY." });
    else if (parseISODate(completionDate)!.getTime() > today.getTime()) messages.push({ level: "error", text: "Completion date is in the future." });
    if (programCode && programCode !== course.code) messages.push({ level: "error", text: `Program code ${programCode} does not match ${course.code}.` });

    let batchId = opts.defaultBatchId;
    if (cohortName) {
      const b = batchByName.get(cohortName.toLowerCase());
      if (!b) messages.push({ level: "error", text: `Cohort “${cohortName}” does not exist for this program.` });
      else batchId = b.id;
    }
    if (ignored.length && i === 0) messages.push({ level: "warning", text: `Column(s) ${ignored.join(", ")} are ignored; issue and expiry dates are set by the system.` });

    const fileKey = `${email}|${batchId ?? `date:${completionDate}`}`;
    if (email && seen.has(fileKey)) messages.push({ level: "error", text: `Duplicate of row ${seen.get(fileKey)} in this file.` });
    else if (email) seen.set(fileKey, rowNumber);

    if (!messages.some((m) => m.level === "error") && completionDate) {
      const student = await db.student.findFirst({ where: { email: { equals: email, mode: "insensitive" } } });
      if (student) {
        if (student.full_name.trim().toLowerCase() !== fullName.toLowerCase()) {
          messages.push({ level: "warning", text: `Existing learner is named “${student.full_name}”; the certificate will show “${fullName}”.` });
        }
        const key = dedupeKey({ studentId: student.id, courseId: course.id, batchId, completionDate: parseISODate(completionDate)! });
        const existing = await db.credential.findFirst({ where: { dedupe_key: key, status: { in: ["ISSUING", "VALID"] } }, select: { certificate_id: true } });
        if (existing) messages.push({ level: "warning", text: `Already has active credential ${existing.certificate_id}. This row will be skipped as a duplicate.` });
      }
      const issues = await preflightCertificate(
        spec,
        {
          learnerName: fullName,
          programName: programTitle,
          completionDate: parseISODate(completionDate)!,
          issueDate: today,
          expiresOn: null,
          certificateId: generateCertificateId({ programCode: course.code, year: today.getUTCFullYear() }),
          verifyUrl: verificationUrl("x".repeat(22)),
        },
        (p) => deps.storage.get(p),
      );
      for (const iss of issues) messages.push({ level: "error", text: `${iss.field === "learner_name" ? "Name" : iss.field}: ${iss.message}` });
    }

    const validation = messages.some((m) => m.level === "error") ? "ERROR" : messages.some((m) => m.level === "warning") ? "WARNING" : "VALID";
    rows.push({
      row_number: rowNumber,
      input: { fullName, email, completionDate: completionDate ?? "", batchId, cohortName, externalRef },
      validation,
      messages,
    });
  }

  const job = await db.$transaction(async (tx) => {
    const j = await tx.credentialBulkJob.create({
      data: {
        course_id: course.id,
        batch_id: opts.defaultBatchId,
        template_id: template.id,
        file_name: opts.fileName.slice(0, 200),
        file_sha256: createHash("sha256").update(opts.bytes).digest("hex"),
        send_email: opts.sendEmail,
        total_rows: rows.length,
        created_by_id: actor.id,
      },
    });
    await tx.credentialBulkRow.createMany({
      data: rows.map((r) => ({
        job_id: j.id,
        row_number: r.row_number,
        input: r.input as unknown as Prisma.InputJsonValue,
        validation: r.validation,
        messages: r.messages as unknown as Prisma.InputJsonValue,
      })),
    });
    return j;
  });
  await db.auditLog.create({
    data: {
      actor_id: actor.id,
      action: "BULK_JOB_VALIDATED",
      entity_type: "credential_bulk_job",
      entity_id: job.id,
      after: { rows: rows.length, errors: rows.filter((r) => r.validation === "ERROR").length, file: job.file_name, sha256: job.file_sha256 },
    },
  });
  return job;
}

export async function confirmBulkJob(jobId: string, actor: StaffUser, deps: CredentialDeps = defaultDeps()) {
  const { db } = deps;
  return db.$transaction(async (tx) => {
    const job = await tx.credentialBulkJob.findUnique({ where: { id: jobId } });
    if (!job) throw new CredentialError("Bulk job not found.", "NOT_FOUND");
    if (job.status !== "VALIDATED") return job; // already confirmed: confirming twice is harmless
    await tx.credentialBulkRow.updateMany({
      where: { job_id: jobId, validation: "ERROR", outcome: "PENDING" },
      data: { outcome: "SKIPPED", error: "Not issued: the row failed validation.", processed_at: new Date() },
    });
    const updated = await tx.credentialBulkJob.update({
      where: { id: jobId },
      data: { status: "PROCESSING", confirmed_by_id: actor.id, confirmed_at: new Date() },
    });
    await tx.auditLog.create({ data: { actor_id: actor.id, action: "BULK_JOB_CONFIRMED", entity_type: "credential_bulk_job", entity_id: jobId } });
    return updated;
  });
}

export async function cancelBulkJob(jobId: string, actor: StaffUser, deps: CredentialDeps = defaultDeps()) {
  const job = await deps.db.credentialBulkJob.findUnique({ where: { id: jobId } });
  if (!job) throw new CredentialError("Bulk job not found.", "NOT_FOUND");
  if (job.status !== "VALIDATED") throw new CredentialError("Only a job that has not been confirmed can be discarded.", "NOT_ALLOWED");
  await deps.db.credentialBulkJob.update({ where: { id: jobId }, data: { status: "CANCELLED" } });
  await deps.db.auditLog.create({ data: { actor_id: actor.id, action: "BULK_JOB_CANCELLED", entity_type: "credential_bulk_job", entity_id: jobId } });
}

const ROW_LEASE_MS = 2 * 60 * 1000;

/**
 * Issue up to `limit` pending rows. Rows are claimed with a short lease so two
 * concurrent callers work on different rows; even if a lease expires mid-row,
 * the deterministic idempotency key makes the second attempt resolve to the
 * same credential.
 */
export async function processBulkChunk(jobId: string, actor: StaffUser, deps: CredentialDeps = defaultDeps(), limit = 10) {
  const { db } = deps;
  const job = await db.credentialBulkJob.findUnique({ where: { id: jobId } });
  if (!job) throw new CredentialError("Bulk job not found.", "NOT_FOUND");
  if (job.status === "VALIDATED") throw new CredentialError("Confirm the job before issuing.", "NOT_ALLOWED");
  if (job.status === "CANCELLED") throw new CredentialError("This job was discarded.", "NOT_ALLOWED");

  const now = deps.now();
  const candidates = await db.credentialBulkRow.findMany({
    where: {
      job_id: jobId,
      outcome: "PENDING",
      validation: { not: "ERROR" },
      OR: [{ processed_at: null }, { processed_at: { lt: new Date(now.getTime() - ROW_LEASE_MS) } }],
    },
    orderBy: { row_number: "asc" },
    take: limit,
  });

  let processed = 0;
  for (const row of candidates) {
    const claim = await db.credentialBulkRow.updateMany({
      where: { id: row.id, outcome: "PENDING", OR: [{ processed_at: null }, { processed_at: { lt: new Date(now.getTime() - ROW_LEASE_MS) } }] },
      data: { processed_at: deps.now() },
    });
    if (claim.count === 0) continue;
    const input = row.input as unknown as RowInput;
    let outcome: "SUCCESS" | "FAILED" | "DUPLICATE" = "FAILED";
    let credentialId: string | null = null;
    let error: string | null = null;
    try {
      const r = await issueCredential(
        {
          fullName: input.fullName,
          email: input.email,
          courseId: job.course_id,
          batchId: input.batchId,
          completionDate: input.completionDate,
          templateId: job.template_id,
          sendEmail: job.send_email,
          idempotencyKey: `bulk:${jobId}:${row.row_number}`,
        },
        actor,
        deps,
        { source: "BULK" },
      );
      credentialId = r.credential.id;
      if (r.credential.status === "VALID") outcome = "SUCCESS";
      else error = r.credential.last_error ?? "Certificate generation failed.";
    } catch (e) {
      if (e instanceof CredentialError) {
        outcome = e.code === "DUPLICATE" ? "DUPLICATE" : "FAILED";
        error = e.message;
      } else {
        console.error("[bulk] row failed", jobId, row.row_number, e);
        error = "Unexpected error while issuing this row.";
      }
    }
    await db.credentialBulkRow.update({ where: { id: row.id }, data: { outcome, credential_id: credentialId, error, processed_at: deps.now() } });
    processed++;
  }

  const remaining = await db.credentialBulkRow.count({ where: { job_id: jobId, outcome: "PENDING", validation: { not: "ERROR" } } });
  if (remaining === 0 && job.status !== "COMPLETED") {
    await db.credentialBulkJob.update({ where: { id: jobId }, data: { status: "COMPLETED", completed_at: deps.now() } });
  }
  return { processed, remaining };
}

/** Put FAILED rows back in the queue. SUCCESS rows are never touched. */
export async function retryFailedRows(jobId: string, actor: StaffUser, deps: CredentialDeps = defaultDeps()) {
  const { db } = deps;
  const n = await db.credentialBulkRow.updateMany({ where: { job_id: jobId, outcome: "FAILED" }, data: { outcome: "PENDING", processed_at: null } });
  if (n.count > 0) await db.credentialBulkJob.update({ where: { id: jobId }, data: { status: "PROCESSING", completed_at: null } });
  await db.auditLog.create({ data: { actor_id: actor.id, action: "BULK_JOB_RETRY", entity_type: "credential_bulk_job", entity_id: jobId, after: { rows: n.count } } });
  return n.count;
}

/** Neutralize spreadsheet formula injection in exported cells. */
export function csvCell(v: string | null | undefined): string {
  let s = v ?? "";
  if (/^[=+\-@\t\r]/.test(s)) s = `'${s}`;
  return /[",\r\n]/.test(s) ? `"${s.replace(/"/g, '""')}"` : s;
}

export async function bulkResultsCsv(jobId: string, includePrivate: boolean, deps: CredentialDeps = defaultDeps()) {
  const rows = await deps.db.credentialBulkRow.findMany({
    where: { job_id: jobId },
    orderBy: { row_number: "asc" },
    include: { credential: { select: { certificate_id: true, verification_token: true, status: true } } },
  });
  const header = ["row", "full_name", ...(includePrivate ? ["email"] : []), "outcome", "certificate_id", "verification_url", "message"];
  const lines = [header.join(",")];
  for (const r of rows) {
    const input = r.input as unknown as RowInput;
    const messages = (r.messages as unknown as RowMessage[]).map((m) => m.text);
    lines.push(
      [
        String(r.row_number),
        csvCell(input.fullName),
        ...(includePrivate ? [csvCell(input.email)] : []),
        r.outcome,
        csvCell(r.credential?.status === "VALID" ? r.credential.certificate_id : ""),
        csvCell(r.credential?.status === "VALID" ? verificationUrl(r.credential.verification_token) : ""),
        csvCell([r.error, ...messages].filter(Boolean).join(" | ")),
      ].join(","),
    );
  }
  return lines.join("\r\n") + "\r\n";
}
