import Link from "next/link";
import { getStaff } from "@/src/lib/auth";
import { can, Permission } from "@/src/lib/permissions";
import { db } from "@/src/lib/db";
import { BULK_COLUMNS, MAX_ROWS } from "@/src/modules/credentials/bulk";
import { createBulkJobAction } from "./actions";
import { Card, Flash, fmtDateTime, inputCls, PageHeader, primaryBtn } from "../_ui";
import { BulkUploadFields } from "./upload-fields";

export const dynamic = "force-dynamic";

export default async function BulkPage({ searchParams }: { searchParams: Promise<Record<string, string | undefined>> }) {
  const staff = await getStaff();
  if (!staff || !can(staff.role, Permission.CredentialsView)) return null;
  if (!can(staff.role, Permission.CredentialsBulkIssue)) return <p className="text-sm text-danger">You do not have permission to bulk issue.</p>;
  const sp = await searchParams;
  const [programs, jobs] = await Promise.all([
    db.course.findMany({
      where: { is_active: true, code: { not: null }, certificate_templates: { some: { status: "ACTIVE" } } },
      orderBy: { name: "asc" },
      select: { id: true, name: true, code: true, batches: { orderBy: { created_at: "desc" }, select: { id: true, name: true } } },
    }),
    db.credentialBulkJob.findMany({
      orderBy: { created_at: "desc" },
      take: 15,
      include: { course: { select: { name: true } }, created_by: { select: { name: true } }, _count: { select: { rows: true } } },
    }),
  ]);

  return (
    <div className="space-y-5">
      <PageHeader title="Bulk issue" subtitle="Upload a cohort, check every row, then confirm. Nothing is issued until you confirm." />
      <Flash error={sp.error} ok={sp.ok === "discarded" ? "Upload discarded. Nothing was issued." : undefined} />

      <div className="grid gap-6 lg:grid-cols-[1fr_340px]">
        <Card>
          {programs.length === 0 ? (
            <p className="text-sm text-muted">No program is ready to issue yet. A program needs a code and an active template.</p>
          ) : (
            <form action={createBulkJobAction} className="space-y-4" encType="multipart/form-data">
              <BulkUploadFields programs={programs} inputCls={inputCls} />
              <label className="block space-y-1.5 text-sm font-semibold text-brand-navy">
                File (.csv or .xlsx, up to {MAX_ROWS} rows)
                <input name="file" type="file" required accept=".csv,text/csv,.xlsx,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" className="block w-full text-sm font-normal" />
              </label>
              <label className="flex items-center gap-2 text-sm"><input type="checkbox" name="sendEmail" defaultChecked className="h-4 w-4 accent-brand-blue" /> Email each learner after their credential is issued</label>
              <button className={primaryBtn}>Upload and validate</button>
            </form>
          )}
        </Card>
        <Card>
          <h2 className="font-display text-lg font-semibold text-brand-navy">File format</h2>
          <p className="mt-2 text-sm text-muted">First row is the header. Required columns:</p>
          <ul className="mt-2 space-y-1 font-mono text-xs">{BULK_COLUMNS.required.map((c) => <li key={c}>{c}</li>)}</ul>
          <p className="mt-3 text-sm text-muted">Optional:</p>
          <ul className="mt-2 space-y-1 font-mono text-xs">{BULK_COLUMNS.optional.map((c) => <li key={c}>{c}</li>)}</ul>
          <p className="mt-3 text-xs text-muted">Dates: YYYY-MM-DD or DD/MM/YYYY. Cohort must match an existing cohort name, or leave it blank to use the default cohort. Certificate IDs are generated by the system and must not be included.</p>
          <a href="/api/admin/credentials/bulk/template" className="mt-4 inline-block text-sm font-semibold text-brand-blue hover:underline">Download the CSV template</a>
        </Card>
      </div>

      <Card>
        <h2 className="font-display text-lg font-semibold text-brand-navy">Recent uploads</h2>
        <table className="mt-3 w-full text-sm">
          <thead className="text-left text-xs uppercase tracking-wide text-muted"><tr><th className="py-2">File</th><th className="py-2">Program</th><th className="py-2">Rows</th><th className="py-2">Status</th><th className="py-2">By</th><th className="py-2">When</th></tr></thead>
          <tbody>
            {jobs.map((j) => (
              <tr key={j.id} className="border-t border-brand-navy/5">
                <td className="py-2"><Link href={`/admin/credentials/bulk/${j.id}`} className="text-brand-blue hover:underline">{j.file_name}</Link></td>
                <td className="py-2">{j.course.name}</td>
                <td className="py-2">{j._count.rows}</td>
                <td className="py-2">{j.status.toLowerCase()}</td>
                <td className="py-2">{j.created_by.name}</td>
                <td className="py-2 text-muted">{fmtDateTime(j.created_at)}</td>
              </tr>
            ))}
            {jobs.length === 0 && <tr><td colSpan={6} className="py-3 text-muted">No uploads yet.</td></tr>}
          </tbody>
        </table>
      </Card>
    </div>
  );
}
